apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hpc-delete
  namespace: argo-events
spec:
  template:
    serviceAccountName: default
  dependencies:
    - name: test-dep
      eventSourceName: hpc-event-source
      eventName: delete
  triggers:
    - template:
        name: argo-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                namespace: default
                generateName: hpc-delete-
                labels:
                  app: resource-workflow
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: cluster
                    # the value will get overridden by the event payload from test-dep
                    value: ""
                  - name: cluster_version
                    # the value will get overridden by the event payload from test-dep
                    value: "3.7.1"
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: cluster
                    - name: cluster_version
                  script:
                    image: public.ecr.aws/parallelcluster/pcluster-api:{{inputs.parameters.cluster_version}}
                    command: [bash]
                    source: |
                      export HPC_CLUSTER_NAME="{{inputs.parameters.cluster}}"
                      echo "HPC_CLUSTER_NAME=$HPC_CLUSTER_NAME"
                      echo -e "{{inputs.parameters.config}}" > config.yaml
                      cat config.yaml
                      pcluster version
                      #env
                      # assume role, set environment variables of the output to use the `example-role` IAM Role
                      #aws sts assume-role --role-arn "arn:aws:iam::123456789012:role/example-role" --role-session-name AWSCLI-Session
                      #pcluster list-clusters
                      pcluster delete-cluster --cluster-name $HPC_CLUSTER_NAME
                    envFrom:
                    - secretRef:
                        name: aws-creds
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.data.cluster }}"
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.data.cluster_version }}"
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3