apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: resource
  namespace: argo-events
spec:
  template:
    serviceAccountName: default
  dependencies:
    - name: test-dep
      eventSourceName: resource
      eventName: example
  triggers:
    - template:
        name: argo-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: resource-workflow-
                labels:
                  app: resource-workflow
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by the event payload from test-dep
                    value: hello world
                  - name: message2
                    # the value will get overridden by the event payload from test-dep
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                    - name: message2
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}","{{inputs.parameters.message2}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.data.FOO }}"
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataTemplate: "{{ .Input.body.data.FOO2 }}"
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3