apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pcluster-describe-cluster
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: cluster_name
      - name: cluster_version
        default: "3.7.1"
      - name: region
        default: "us-east-2"
      - name: options
        default: ""
    script:
      image: public.ecr.aws/parallelcluster/pcluster-api:{{inputs.parameters.cluster_version}}
      command: [bash]
      source: |
        #pcluster version
        #env
        pcluster describe-cluster \
        --cluster-name "{{inputs.parameters.cluster_name}}" \
        --region {{inputs.parameters.region}} {{inputs.parameters.options}}
      envFrom:
      - secretRef:
          name: aws-creds