apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pcluster-update-compute-fleet
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: cluster_version
      default: "3.7.1"
    - name: cluster
    #{START_REQUESTED,STOP_REQUESTED,ENABLED,DISABLED}
    - name: status
  templates:
  - name: main
    script:
      image: public.ecr.aws/parallelcluster/pcluster-api:{{workflow.parameters.cluster_version}}
      command: [bash]
      source: |
        export HPC_CLUSTER_NAME="{{workflow.parameters.cluster}}"
        echo "HPC_CLUSTER_NAME=$HPC_CLUSTER_NAME"
        export HPC_STATUS="{{workflow.parameters.status}}"
        echo "HPC_STATUS=$HPC_STATUS"
        pcluster version
        #env
        pcluster update-compute-fleet --status $HPC_STATUS --cluster-name $HPC_CLUSTER_NAME
      envFrom:
      - secretRef:
          name: aws-creds