apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: update-compute-fleet-hpc
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: cluster
      value: my-cluster
    - name: status
  templates:
  - name: main
    script:
      image: public.ecr.aws/parallelcluster/pcluster-api:3.7.1
      command: [bash]
      source: |
        pcluster version
        pcluster update-compute-fleet --cluster-name $HPC_CLUSTER_NAME --status "{{workflow.parameters.status}}"
      env:
      - name: HPC_CLUSTER_NAME
        value: "{{workflow.parameters.cluster}}"
      envFrom:
      - secretRef:
          name: aws-creds
