apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: pcluster-event-source
  namespace: argo-events
spec:
  template:
    serviceAccountName: default # assign a service account with `get`, `list` and `watch` permissions on the resource being watched.
  resource:
    add:
      # namespace to listen events within
      #namespace: hpc
      # resource group
      group: ''
      # resource version
      version: v1
      # resource kind
      resource: configmaps
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - ADD
      # optional.
      filter:
        # This indicates only watch the events happened after the service start time.
        afterStart: true
        # labels provide listing options to K8s API to watch objects
        labels:
          - key: app
            # Supported operations like ==, !=, etc.
            # Defaults to ==.
            # Refer https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors for more info.
            # optional.
            operation: "=="
            value: pcluster
    update:
      # namespace to listen events within
      #namespace: hpc
      # resource group
      group: ''
      # resource version
      version: v1
      # resource kind
      resource: configmaps
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - UPDATE
      # optional.
      filter:
        # This indicates only watch the events happened after the service start time.
        afterStart: true
        # labels provide listing options to K8s API to watch objects
        labels:
          - key: app
            # Supported operations like ==, !=, etc.
            # Defaults to ==.
            # Refer https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors for more info.
            # optional.
            operation: "=="
            value: pcluster
    delete:
      # namespace to listen events within
      #namespace: hpc
      # resource group
      group: ''
      # resource version
      version: v1
      # resource kind
      resource: configmaps
      # type of events
      # possible values are ADD, DELETE, UPDATE
      # Optional
      eventTypes:
        - DELETE
      # optional.
      filter:
        # This indicates only watch the events happened after the service start time.
        afterStart: true
        # labels provide listing options to K8s API to watch objects
        labels:
          - key: app
            # Supported operations like ==, !=, etc.
            # Defaults to ==.
            # Refer https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors for more info.
            # optional.
            operation: "=="
            value: pcluster
